config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:new, :create, :index, :show]
  resources :users, only: [:new, :create, :show, :index] do
    resources :activities
  end

  resources :sessions
  resources :categories do
    resources :activities
  end
  resources :activities do
    collection do
      get 'short_to_long'
    end
  end

  get '/sign_in', to: "sessions#new"
  post '/sessions', to: "sessions#create"
  get '/sign_out', to: "sessions#destroy"
  root 'sessions#home', as: 'home'
  get '/auth/facebook/callback' => 'sessions#create'

  get '/activities/:id/activity_data', to: 'activities#activity_data'

  get '/users/:id/activities/new', to: 'users#new_activity'
end

app/models/activities_topics.rb
class ActivityTopic < ApplicationRecord
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :activity_topics
  has_many :topics, through: :activity_topics

  validates :title, length: {in: 1..50}
  validates :description, presence: true
  validates :time, presence: true
  validates_associated :category, presence: true
  validates_associated :topics, presence: true

  def topics_attributes=(topics_attributes)
    topics_attributes.each do |i, topic_attributes|
      if topic = Topic.find_by(name: topic_attributes[:name])
        if !self.topics.find_by(name: topic[:name])
          self.topics << topic
        end
      else
        self.topics.build(topic_attributes)
      end
    end
  end

  def self.short_to_long
    all.order(time: :asc)
  end

  def self.alpha
    order(title: :asc)
  end
end

app/models/activity_topic.rb
class ActivityTopic < ApplicationRecord
  belongs_to :activity
  belongs_to :topic
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :activities
  has_many :users, through: :activities
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :activity_topics
  has_many :activities, through: :activity_topics
  validates :name, length: {maximum: 25, message: "Topic name has 25 character maximum"}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :activities
  has_many :categories, through: :activities

  validates :username, uniqueness: {message: "This username is taken"}
  validates :username, length: {minimum: 6}
  validates :email, uniqueness: {message: "This email is taken"}
  validates :email, presence: true

  def self.find_or_create_by_omniauth(auth_hash)
    oauth_email = auth_hash["info"]["email"]
    if user = User.find_by(email: oauth_email)
      return user
    else
      user = User.create(email: oauth_email, password: SecureRandom.hex)
    end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :find_activity, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  def short_to_long
    @activities = Activity.short_to_long
  end

  def new
    @activity = Activity.new
    @activity.topics.build
  end

  def create
    @activity = current_user.activities.build(activity_params)
    if @activity.save
      respond_to do |f|
        f.html {redirect_to activity_path(@activity)}
        f.json {render json: @activity}
      end

    else
      render 'new'
    end
  end

  def index
    @activities = Activity.all
    if @category = Category.find_by(id: params[:category_id])
      @activities = @category.activities.alpha
    else
      respond_to do |f|
        f.html {render :index}
        f.json {render json: @activities}
      end
    end
  end

  def show
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @activity}
    end
  end

  def activity_data
    @activity = Activity.find(params[:id])
    render json: ActivitySerializer.serialize(@activity)
  end

  def edit
  end

  def update
    if @activity.update(activity_params)
      redirect_to activity_path(@activity)
    else
      render 'edit'
    end
  end

  def destroy
    @activity.destroy
    redirect_to activities_path
  end



private
  def find_activity
    @activity = Activity.find_by(id: params[:id])
  end

  def activity_params
    params.require(:activity).permit(:title, :description, :goal, :rules, :time, :category_id, topics_attributes: [:name])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def require_login
    if !current_user
      flash[:message] = "Please sign in."
      redirect_to home_path
    end
  end

  helper_method :require_login
  helper_method :current_user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_login

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @category}
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      redirect_to categories_path
    end
  end

  def create
    if auth_hash = request.env["omniauth.auth"]
      user = User.find_or_create_by_omniauth(auth_hash)
      session[:user_id] = user.id
      redirect_to categories_path
    else
      user = User.find_by(email: params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        flash[:message] = "Welcome back!"
        redirect_to categories_path
      else
        redirect_to '/sessions/new'
      end
    end
  end

  def home
    @activity = Activity.order("RANDOM()").first
  end

  def show
    @user = current_user.username
  end

  def destroy
    reset_session
    redirect_to sign_in_path
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :require_login

  def new
    @topic = Topic.new
  end

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find_by(id: params[:id])
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @topic}
    end
  end

  def create
    @topic = Topic.create(topic_params)
  end

private
  def topic_params
    params.require(:topic).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show, :index]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:message] = "Welcome!"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  # ToDO:
  # 1. is move this JSON API route to /users/:user_id/activities
  # 2. Sorting the activities by time_needed in your JS
  def show
    @activity = Activity.new
    @activity.topics.build
    @user = User.find_by(id: params[:id])
  end

  def index
    @user = User.find_by(id: params[:id])
  end

private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_form.html.erb
<% if @activity.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>
    <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <%end%>
    </ul>
  </div>
<%end%>

<%= form_for activity do |f| %>
  <%= f.label "Title (required)" %><br>
  <%= f.text_field :title %> <br>
  <%= f.label "Description (required)" %><br>
  <%= f.text_area :description %><br>
  <%= f.label :goal %><br>
  <%= f.text_field :goal %><br>
  <%= f.label :rules %><br>
  <%= f.text_area :rules %><br>
  <%= f.label "Time (required)" %><br>
  <%= f.number_field :time %><br>
  <%= f.label "Category (required)" %><br>
  <%= f.collection_select :category_id, Category.all, :id, :name %><br>
  <%= f.fields_for :topics do |field|%>
    <%= field.label "Topic" %><br>
    <%= field.text_field :name %><br>
  <%end%>
  <br>
  <%= submit_tag "Submit"%>
<%end%>

app/views/activities/edit.html.erb
<h1>Edit Activity</h1>

<% if current_user == @activity.user %>
  <%= render partial: 'form', locals: {activity: @activity} %>
<% else %>
  <h3>Sorry, you can only edit your own activities.</h3>
  <%= link_to "Back to activities", category_activities_path %>
<% end %>

app/views/activities/index.html.erb
<h1>Activities</h1>

<h3><%= link_to "Shortest to Longest", short_to_long_activities_path %></h3>
<h3><%= link_to 'Create New Activity', new_activity_path %></h3>

<% @activities.each do |act| %>
  <a class="activity_show" href='/activities/<%=act.id%>'><%=act.title%></a><br>
<% end %>

app/views/activities/new.html.erb
<h1>New Activity</h1>
<%= render partial: 'form', locals: {activity: @activity} %>

app/views/activities/order.html.erb
<h1>Activities</h1>
<p>(shortest to longest activity)</p>
<h3><%= link_to 'Create New Activity', new_activity_path %></h3>

<% @activities.each do |act| %>
  <%= link_to act.title, activity_path(act) %><br>
<% end %>

app/views/activities/short_to_long.html.erb
<h1>Activities by Time</h1>

<% @activities.each do |act| %>
  <%= act.time %> min. - <%= link_to act.title, activity_path(act) %><br>
<% end %>

app/views/activities/show.html.erb
<h1 class="title"> <%=@activity.title%> </h1>

<a href="#" class="js-next" data-id='<%=@activity.id%>'>Next...</a>
<input class="nextId" type="hidden" data-id="<%=@nextId%>"></input>

<h4>Description: </h4>
<p class="description"><%=@activity.description%></p>
<h4>Goal: </h4>
<p class="goal"><%=@activity.goal%></p>
<h4>Rules: </h4>
<p class="rules"><%=@activity.rules%></p>
<h4>Time Needed:</h4>
<p class="time"><%=@activity.time%> minutes</p>
<h4>Category:</h4>
<p class="category"><%=@activity.category.name%></p>
<h4>Topics:</h4>
<p class="topics"></p>
<div class="topic-div">
<%@activity.topics.each do |top|%>
  <%=top.name%>
<%end%>
</div>
<br><br>

<%if current_user == @activity.user %>
  <%= link_to "Edit Activity", edit_activity_path %>
  <%= link_to "Delete Activity", activity_path(@activity), method: :delete %>
<%end%>

app/views/categories/index.html.erb
<h1>Categories</h1>

<%@categories.each do |cat|%>
  <h3><%= link_to cat.name, category_path(cat)%></h3>
<%end%>

app/views/categories/show.html.erb
<h1> <%=@category.name%></h1>

<h3><%= link_to 'Create New Activity', new_category_activity_path(@category) %></h3>

<%@category.activities.each do |act| %>
  <%= link_to act.title, category_activity_path(act)%><br>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamBuildingRails</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>
  <body>
    <% if current_user %>
      <%= link_to 'Activities', activities_path %>
      <%= link_to 'Categories', categories_path %>
      <%= link_to 'Topics', topics_path %>
      <%= link_to "#{current_user.username}", user_path(current_user) %>
      <%= link_to 'Sign Out', sign_out_path %>
    <%end%>
    <br><br>
    <%= flash[:message] %>
    <%= yield %>
  </body>
</html>

app/views/topics/index.html.erb
<h1>Topics</h1>

<% @topics.each do |top| %>
  <h3><%=link_to top.name, topic_path(top)%></h3>
<%end%>

app/views/topics/show.html.erb
<h1><%=@topic.name%></h1>

<%@topic.activities.each do |act| %>
  <%= link_to act.title, activity_path(act)%><br>
<%end%>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <%end%>
    </ul>
  </div>
<%end%>

<%= form_for @user do |f| %>
  Username: <br>
  <%= f.text_field :username %><br>
  Email: <br>
  <%= f.text_field :email %><br>
  Password: <br>
  <%= f.password_field :password %><br>
  Password Confirmation: <br>
  <%= f.password_field :password_confirmation %><br><br>
  <%= f.submit "Submit" %>
<% end %>

<br>
<%= link_to "Sign In", sign_in_path %>
<%= link_to('Log in with Facebook', '/auth/facebook') %>

app/views/users/show.html.erb
<h4><a id="create_link" href="#">Create New Activity</a></h4>

<div class="activityForm">
<%= form_for @activity do |f| %>
  <%= f.label "Title (required)" %><br>
  <%= f.text_field :title %> <br>
  <%= f.label "Description (required)" %><br>
  <%= f.text_area :description %><br>
  <%= f.label :goal %><br>
  <%= f.text_field :goal %><br>
  <%= f.label :rules %><br>
  <%= f.text_area :rules %><br>
  <%= f.label "Time (required)" %><br>
  <%= f.number_field :time %><br>
  <%= f.label "Category (required)" %><br>
  <%= f.collection_select :category_id, Category.all, :id, :name %><br>
  <%= f.fields_for :topics do |field|%>
    <%= field.label "Topic" %><br>
    <%= field.text_field :name %><br>
  <%end%>
  <br>
  <%= submit_tag "Create Activity" %>
<%end%>
</div>


<h3 class="username_activities" data-id="<%=@user.id%>"> <%=@user.username%>'s Activities</h3>
<ul id="activity_list">

</ul>

<div class="showActivity">
  <p> Please pick an activity to find out more information about it</p>
</div>
  <br><br>


  <%if current_user == @activity.user %>
  <%= link_to "Edit Activity", edit_activity_path %>
  <%= link_to "Delete Activity", activity_path(@activity), method: :delete %>
  <%end%>
</div>